#!/usr/bin/env sh

# taps
brew tap homebrew/binary
brew tap homebrew/dupes
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/versions
brew tap marksteve/personal
brew tap mopidy/mopidy
brew tap neovim/neovim
brew tap thoughtbot/formulae

# packages
brew install ack
brew install autoconf
brew install automake
brew install bash-completion
brew install bazaar
brew install bison
brew install boost
brew install boost-python
brew install brew-backup --HEAD
brew install brew-cask
brew install cairo
brew install cmake
brew install cscope
brew install docker
brew install eigen
brew install ffmpeg
brew install fish
brew install flow
brew install fontconfig
brew install fpp
brew install freetype
brew install gcc
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install git
brew install glfw3
brew install glib
brew install gmp
brew install gnupg
brew install go
brew install gobject-introspection
brew install harfbuzz
brew install heroku-toolbelt
brew install hub --HEAD
brew install icdiff
brew install icu4c
brew install ilmbase
brew install imagemagick
brew install isl
brew install jpeg
brew install jq
brew install lame
brew install libffi
brew install libmpc
brew install libpng
brew install libspotify
brew install libtiff
brew install libtool
brew install libvo-aacenc
brew install libyaml
brew install lsyncd
brew install lua
brew install macvim
brew install mercurial
brew install mitmproxy
brew install mpfr
brew install neovim --HEAD
brew install ngrok
brew install nmap
brew install numpy
brew install opencv
brew install openexr
brew install openssl
brew install pango
brew install pcre
brew install pick
brew install pixman
brew install pkg-config
brew install portaudio
brew install postgresql
brew install pv
brew install pwgen
brew install pypy
brew install python3
brew install readline
brew install realpath
brew install redis
brew install rsync
brew install sqlite
brew install syncthing
brew install tarsnap
brew install the_silver_searcher
brew install tig
brew install watchman
brew install wget
brew install x264
brew install xvid
brew install xz
brew install youtube-dl
brew install zsh
