#!/usr/bin/env sh

# taps
brew tap homebrew/binary
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/fuse
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/versions
brew tap infinit/releases
brew tap marksteve/personal
brew tap mopidy/mopidy
brew tap neovim/neovim
brew tap thoughtbot/formulae

# packages
brew install ack
brew install adns
brew install autoconf
brew install automake
brew install bash-completion
brew install bazaar
brew install bison
brew install boost
brew install boost-python
brew install brew-backup --HEAD
brew install caddy
brew install cairo
brew install choose-gui
brew install cmake
brew install consul
brew install cscope
brew install devd
brew install docker
brew install docker-compose
brew install docker-machine
brew install doctl
brew install duplicity
brew install eigen
brew install fabio
brew install ffmpeg
brew install fish
brew install flow
brew install fontconfig
brew install fpp
brew install freetype
brew install fribidi
brew install gcc
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install git
brew install glfw3
brew install glib
brew install gmp
brew install gnupg21
brew install gnutls
brew install go
brew install gobject-introspection
brew install graphicsmagick
brew install harfbuzz
brew install heroku
brew install httpie
brew install hub --HEAD
brew install icdiff
brew install icu4c
brew install ilmbase
brew install imagemagick
brew install infinit
brew install isl
brew install jpeg
brew install jq
brew install keybase
brew install lame
brew install ledger
brew install libass
brew install libassuan
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libksba
brew install libmpc
brew install libogg
brew install libpng
brew install librsync
brew install libsass
brew install libspotify
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvo-aacenc
brew install libvorbis
brew install libxml2
brew install libyaml
brew install little-cms2
brew install lsyncd
brew install lua
brew install mariadb
brew install mercurial
brew install mitmproxy
brew install mpfr
brew install mpv
brew install neovim
brew install nettle
brew install nginx
brew install ngrok
brew install ngrok2
brew install nmap
brew install npth
brew install ntfs-3g
brew install numpy
brew install oniguruma
brew install opencv3 --HEAD
brew install openexr
brew install openssl
brew install pango
brew install pcre
brew install pick
brew install pinentry
brew install pinentry-mac
brew install pixman
brew install pkg-config
brew install popt
brew install portaudio
brew install portmidi
brew install postgresql
brew install pth
brew install pv
brew install pwgen
brew install py2cairo
brew install pypy
brew install python3
brew install readline
brew install realpath
brew install redis
brew install rename
brew install rethinkdb
brew install rsync
brew install ruby
brew install sassc
brew install sdl
brew install sdl2
brew install sdl_image
brew install sdl_mixer
brew install sdl_ttf
brew install sqlite
brew install sshuttle
brew install syncthing
brew install tarsnap
brew install texi2html
brew install the_silver_searcher
brew install tig
brew install webp
brew install wget
brew install wifi-password
brew install wxmac
brew install x264
brew install xonsh
brew install xvid
brew install xz
brew install yasm
brew install youtube-dl
brew install zsh
