#!/usr/bin/env sh

# taps
brew tap ==> Auto-updated Homebrew!
brew tap Updated 5 taps (homebrew/core, homebrew/dupes, homebrew/fuse, homebrew/science, homebrew/versions).
brew tap ==> New Formulae
brew tap armor
brew tap homebrew/science/fermi-lite
brew tap homebrew/science/kaiju
brew tap homebrew/science/mothur
brew tap hostess
brew tap kube-aws
brew tap p11-kit
brew tap ripgrep
brew tap ==> Updated Formulae
brew tap aha
brew tap algernon
brew tap anjuta
brew tap ansible
brew tap at-spi2-atk
brew tap at-spi2-core
brew tap atk
brew tap autojump
brew tap aws-sdk-cpp
brew tap awscli
brew tap baobab
brew tap brew-gem
brew tap c-ares
brew tap calabash
brew tap ccache
brew tap checkstyle
brew tap crystal-lang
brew tap devhelp
brew tap file-roller
brew tap flow
brew tap format-udf
brew tap freeipmi
brew tap freeradius-server
brew tap gammaray
brew tap gdk-pixbuf
brew tap gdl
brew tap gitg
brew tap gjs
brew tap glib
brew tap glibmm
brew tap glm
brew tap gnome-builder
brew tap gspell
brew tap gssdp
brew tap gtksourceview3
brew tap gxml
brew tap homebrew/science/gap
brew tap homebrew/science/gnudatalanguage
brew tap homebrew/science/nest
brew tap homebrew/science/nexusformat
brew tap homebrew/science/octave
brew tap homebrew/science/pspp
brew tap homebrew/science/qcl
brew tap homebrew/science/r
brew tap homebrew/versions/guile18
brew tap homebrew/versions/percona-server55
brew tap homebrew/versions/postgresql93
brew tap homebrew/versions/postgresql94
brew tap homebrew/versions/ruby187
brew tap homebrew/versions/ruby192
brew tap homebrew/versions/ruby193
brew tap homebrew/versions/ruby20
brew tap homebrew/versions/ruby21
brew tap homebrew/versions/ruby22
brew tap homebrew/versions/spidermonkey45
brew tap homebrew/versions/tomcat7
brew tap imapsync
brew tap jack
brew tap kitchen-sync
brew tap kobalt
brew tap kotlin
brew tap libcouchbase
brew tap libgit2-glib
brew tap libpeas
brew tap libsigc++
brew tap liquibase
brew tap media-info
brew tap mediaconch
brew tap metashell
brew tap nettle
brew tap nim
brew tap noti
brew tap oniguruma
brew tap openrtsp
brew tap pgroonga
brew tap pygobject3
brew tap re2
brew tap repo
brew tap rolldice
brew tap ruby
brew tap rush
brew tap rust
brew tap sbcl
brew tap shadowsocks-libev
brew tap sqlmap
brew tap tcpkali
brew tap telegraf
brew tap tmux
brew tap vala
brew tap valabind
brew tap vdirsyncer
brew tap vim
brew tap vte3
brew tap wimlib
brew tap xonsh
brew tap youtube-dl
brew tap zenity
brew tap ==> Deleted Formulae
brew tap homebrew/versions/gnuplot4
brew tap homebrew/versions/ruby182
brew tap homebrew/versions/ruby186
brew tap jless
brew tap trang
brew tap 
brew tap homebrew/binary
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/fuse
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/versions
brew tap infinit/releases
brew tap laurent22/massren
brew tap mopidy/mopidy
brew tap neovim/neovim
brew tap thoughtbot/formulae

# packages
brew install ack
brew install adns
brew install ansible
brew install autoconf
brew install automake
brew install bash-completion
brew install bazaar
brew install bison
brew install boost
brew install boost-python
brew install brew-backup --HEAD
brew install caddy
brew install cairo
brew install cctools
brew install cgal
brew install choose-gui
brew install cmake
brew install consul
brew install coreutils
brew install cscope
brew install devd
brew install distribution
brew install docker
brew install docker-compose
brew install docker-machine
brew install doctl
brew install duplicity
brew install eigen
brew install fabio
brew install ffmpeg
brew install flow
brew install fontconfig
brew install fpp
brew install freetype
brew install freexl
brew install fribidi
brew install fzf
brew install gcc
brew install gdal
brew install gdbm
brew install gdk-pixbuf
brew install geos
brew install gettext
brew install giflib
brew install git
brew install glfw3
brew install glib
brew install gmp
brew install gnupg21
brew install gnutls
brew install go
brew install gobject-introspection
brew install graphicsmagick
brew install harfbuzz
brew install heroku
brew install httpie
brew install hub
brew install icdiff
brew install icu4c
brew install ilmbase
brew install imagemagick
brew install infinit
brew install isl
brew install jpeg
brew install jq
brew install json-c
brew install keybase
brew install lame
brew install ledger
brew install libass
brew install libassuan
brew install libffi
brew install libgcrypt
brew install libgeotiff
brew install libgpg-error
brew install libksba
brew install liblwgeom
brew install libmpc
brew install libogg
brew install libpng
brew install librsync
brew install libsass
brew install libspatialite
brew install libspotify
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvo-aacenc
brew install libvorbis
brew install libxml2
brew install libyaml
brew install little-cms2
brew install lsyncd
brew install lua
brew install lzlib
brew install mariadb
brew install mitmproxy
brew install mpfr
brew install mpv
brew install neovim
brew install nettle
brew install nginx
brew install ngrok
brew install ngrok2
brew install nmap
brew install npth
brew install ntfs-3g
brew install numpy
brew install oniguruma
brew install opencv3 --HEAD
brew install openexr
brew install openssl
brew install pango
brew install pcre
brew install pick
brew install pinentry
brew install pinentry-mac
brew install pixman
brew install pkg-config
brew install popt
brew install portaudio
brew install portmidi
brew install postgresql
brew install proj
brew install pth
brew install pv
brew install pwgen
brew install py2cairo
brew install pypy
brew install python3
brew install readline
brew install redis
brew install rename
brew install rethinkdb
brew install rsync
brew install sassc
brew install sdl
brew install sdl2
brew install sdl_image
brew install sdl_mixer
brew install sdl_ttf
brew install sfcgal
brew install sqlite
brew install sshuttle
brew install syncthing
brew install tarsnap
brew install texi2html
brew install the_silver_searcher
brew install tig
brew install webp
brew install wget
brew install wifi-password
brew install wxmac
brew install x264
brew install xonsh
brew install xvid
brew install xz
brew install yasm
brew install youtube-dl
brew install zsh
