[tools]
node = "22"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:turbo" = "latest"
"npm:instant-cli" = "latest"
"npm:sv" = "latest"
"npm:taze" = "latest"
"npm:slogtail" = "latest"
"npm:pnpm" = "11"
"npm:@earendil-works/pi-coding-agent" = "latest"

[settings]
experimental = true
