[tools]
node = "20"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:turbo" = "latest"
"npm:instant-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
experimental = true
