#!/bin/bash
set -x
ulimit -n 1024
PATH=$PATH:/usr/local/bin
DUPLICITY="duplicity --s3-use-new-style --allow-source-mismatch --encrypt-key DFC1C9A1"
$DUPLICITY $HOME/Dropbox/Secrets s3+http://marksteve/Secrets
$DUPLICITY $HOME/Keys s3+http://marksteve/Keys
tarsnap-backup() {
  tarsnap -v --humanize-numbers -c -f $(realpath "$1"):$(date -u +%s) $1
}
tarsnap-backup $HOME/Dropbox/Secrets
tarsnap-backup $HOME/Keys
