#!/bin/bash
set -x
ulimit -n 1024
PATH=$PATH:/usr/local/bin

duplicity \
  --s3-use-new-style \
  --allow-source-mismatch \
  --encrypt-key DFC1C9A1 \
  $HOME/Secrets \
  s3+http://marksteve/Secrets

tarsnap-backup() {
  tarsnap -v --humanize-numbers -c -f $(realpath "$1"):$(date -u +%s) $1
}
tarsnap-backup $HOME/Secrets
