#!/bin/bash
set -ex
export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.secrets/backups-sa-key.json
restic --repo gs:marksteve:/secrets.enc backup $HOME/.secrets.enc
restic --repo s3:https://s3.amazonaws.com/marksteve/secrets.enc backup $HOME/.secrets.enc
