for F in exports aliases functions; do
  F=$HOME/.$F
  [ -e "$F" ] && source $F
done

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# http://www.reddit.com/r/commandline/comments/kbeoe/you_can_make_readline_and_bash_much_more_user/
bind 'set completion-ignore-case on'
bind 'set completion-prefix-display-length 2'

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# git branch in prompt
command -v git >/dev/null && PS1="$PS1\$(__git_ps1 '[%s] ')"

# virtualenvwrapper
source virtualenvwrapper.sh
