# antigen
source $HOME/Dotfiles/antigen/antigen.zsh
antigen use oh-my-zsh

antigen theme wezm
antigen bundle colorize
antigen bundle copydir
antigen bundle copyfile
antigen bundle ssh-agent

antigen bundle rimraf/k

antigen apply

# imports
for F in exports aliases functions; do
  F=$HOME/.$F
  [ -e "$F" ] && source $F
done

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


# added by travis gem
[ -f /Users/marksteve/.travis/travis.sh ] && source /Users/marksteve/.travis/travis.sh
