# antigen
source $HOME/Dotfiles/antigen/antigen.zsh
antigen use oh-my-zsh

antigen use oh-my-zsh
antigen theme wezm
antigen bundle colorize
antigen bundle copydir
antigen bundle copyfile
antigen bundle ssh-agent

antigen apply

# asdf
source $HOME/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash

# imports
for F in exports aliases functions; do
  F=$HOME/.$F
  [ -e "$F" ] && source $F
done

# Fix ssh-agent not working on tmux reattach
if [[ -S "$SSH_AUTH_SOCK" && ! -h "$SSH_AUTH_SOCK" ]]; then
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock;
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock;

# added by travis gem
[ -f /Users/marksteve/.travis/travis.sh ] && source /Users/marksteve/.travis/travis.sh

